["bin/antigen.zsh"]
type = "file"
url = "https://git.io/antigen"
refreshPeriod = "168h"

["bin/git-prompt.sh"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
refreshPeriod = "168h"

[".local/share/nvim/site/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"
